// Generated by CoffeeScript 1.8.0
var argv, usage;

usage = "\nUsage: consul-restore [consul http address]\n\n  Copy the current directory's files and folders into consul's key value store\n";

argv = process.argv.slice(2);

if (argv.length !== 1) {
  console.error(usage);
  process.exit(1);
}
